--La liste des produits commandés par le labo 1 au fournisseur "Fournitout".--

SELECT DISTINCT ID_PRODUIT FROM PRODUIT WHERE ID_PRODUIT IN(
    SELECT ID_PRODUIT FROM COMMANDE WHERE IDLABORATOIRE IN(
    SELECT IDLABORATOIRE FROM LABORATOIRE WHERE NOMLABO LIKE 'Labo 1')
    AND IDFOURNISSEUR IN(
    SELECT IDFOURNISSEUR FROM FOURNISSEUR WHERE NOMFOURNISSEUR LIKE 'Fournitout')
    );
    
--Les dates et heures de réunion du chercheur Clément Turpin (emploi du temps)--
SELECT DATEREUNION,TO_CHAR(HEUREREUNION,'HH24:MI') AS HEUREREUNION FROM REUNION_LABORATOIRE WHERE IDREUNION IN (
    SELECT IDREUNION FROM PARTICIPER_REUNION WHERE IDCHERCHEUR IN(
    SELECT IDCHERCHEUR FROM CHERCHEUR WHERE NOMCHERCHEUR LIKE 'Turpin' AND PRENOMCHERCHEUR LIKE 'Clément'
    )
)



--La liste des produits utilisés dans l'expérience du projet mené par l'équipe dont la chercheur Josiane Cardin est membre.--
SELECT DISTINCT  NOMCONSOMMABLE,NOM_MAT_BIO,NOMPRODUITCHIMIQUE FROM ENZYMES_RESTRICTION,MATERIEL_BIOLOGIE_MOLECULAIRE,CULTURECELLULAIRE,CONSOMMABLES,PRODUITSCHIMIQUES
WHERE (IDCONSOMMABLE)  IN (
    SELECT IDCONSOMMABLE FROM PRODUIT WHERE ID_PRODUIT IN(
    SELECT ID_PRODUIT FROM UTILISER WHERE IDEXPERIENCE IN(
    SELECT IDEXPERIENCE FROM PROJET WHERE IDPROJET IN(
    SELECT IDPROJET FROM EQUIPE WHERE IDEQUIPE IN(
    SELECT IDEQUIPE FROM ETRE_MEMBRE WHERE IDCHERCHEUR IN(
    SELECT IDCHERCHEUR FROM CHERCHEUR WHERE NOMCHERCHEUR LIKE 'Cardin' AND PRENOMCHERCHEUR LIKE 'Josiane'
    )
    )
    )
    )
    ))
AND ID_MAT_BIO IN(
    SELECT ID_MAT_BIO FROM PRODUIT WHERE ID_PRODUIT IN(
    SELECT ID_PRODUIT FROM UTILISER WHERE IDEXPERIENCE IN(
    SELECT IDEXPERIENCE FROM PROJET WHERE IDPROJET IN(
    SELECT IDPROJET FROM EQUIPE WHERE IDEQUIPE IN(
    SELECT IDEQUIPE FROM ETRE_MEMBRE WHERE IDCHERCHEUR IN(
    SELECT IDCHERCHEUR FROM CHERCHEUR WHERE NOMCHERCHEUR LIKE 'Cardin' AND PRENOMCHERCHEUR LIKE 'Josiane'
    )
    )
    )
    )
    )
    )
AND IDPRODUITCHIMIQUE IN(
    SELECT IDPRODUITCHIMIQUE FROM PRODUIT WHERE ID_PRODUIT IN(
    SELECT ID_PRODUIT FROM UTILISER WHERE IDEXPERIENCE IN(
    SELECT IDEXPERIENCE FROM PROJET WHERE IDPROJET IN(
    SELECT IDPROJET FROM EQUIPE WHERE IDEQUIPE IN(
    SELECT IDEQUIPE FROM ETRE_MEMBRE WHERE IDCHERCHEUR IN(
    SELECT IDCHERCHEUR FROM CHERCHEUR WHERE NOMCHERCHEUR LIKE 'Cardin' AND PRENOMCHERCHEUR LIKE 'Josiane'
    )
    )
    )
    )
    )
    )

--La liste des fournisseurs ayant fourni tous les laboratoires--
SELECT NOMFOURNISSEUR FROM FOURNISSEUR WHERE IDFOURNISSEUR IN(
    SELECT IDFOURNISSEUR FROM COMMANDE c1 WHERE NOT EXISTS(
    SELECT IDFOURNISSEUR FROM COMMANDE c2 WHERE NOT EXISTS(
    SELECT IDLABORATOIRE FROM COMMANDE c3 WHERE (c3.IDLABORATOIRE=c2.IDLABORATOIRE AND c3.IDFOURNISSEUR=c1.IDFOURNISSEUR)
    
    )
    )
)
--La liste des produits fournis par un fournisseur dont le numéro de téléphone contient en 7--
SELECT DISTINCT ID_PRODUIT FROM COMMANDE WHERE IDFOURNISSEUR IN(
    SELECT IDFOURNISSEUR FROM FOURNISSEUR WHERE REGEXP_LIKE(FOURNISSEUR.TELFOURNISSEUR, '[012345679]*7[012345679]')
)

--Les chercheurs ingénieurs faisant parti des équipes dirigés par Beatrice Hector : --
SELECT DISTINCT NOMCHERCHEUR,PRENOMCHERCHEUR FROM CHERCHEUR WHERE (NOMCHERCHEUR NOT LIKE 'Hector' AND PRENOMCHERCHEUR NOT LIKE 'Beatrice' AND IDCHERCHEUR IN(
    SELECT IDCHERCHEUR FROM ETRE_MEMBRE WHERE IDEQUIPE IN(
    SELECT IDEQUIPE FROM EQUIPE WHERE IDCHERCHEUR IN(
    SELECT IDCHERCHEUR FROM CHERCHEUR WHERE (NOMCHERCHEUR LIKE 'Hector' AND PRENOMCHERCHEUR LIKE 'Beatrice')
    )
)
)
    )

--Le nombre de chercheurs qui ont une réunion de programmée le 24 novembre 2023--

SELECT COUNT (IDCHERCHEUR) FROM CHERCHEUR WHERE IDCHERCHEUR IN(
    SELECT IDCHERCHEUR FROM PARTICIPER_REUNION  WHERE IDREUNION IN(
    SELECT IDREUNION FROM REUNION_LABORATOIRE WHERE DATEREUNION = TO_DATE('24112023','DDMMYYYY')
    )GROUP BY IDCHERCHEUR
)

--La moyenne des quantités des produits disponibles au sein du labo 2--
SELECT AVG(nb_restant_produit) FROM PRODUIT WHERE IDLABORATOIRE IN (
    SELECT IDLABORATOIRE FROM LABORATOIRE WHERE NOMLABO LIKE 'Labo 2'
)