--Ce document contient les différentes requêtes afin de supprimer les données et/ou les tables dans la base de données--

--Ces requêtes sont ici à titre d'exemple, certaines pouvant entraîner des erreurs suites à des problèmes de clés étrangères--
INSERT INTO LABORATOIRE(IDLABORATOIRE, NOMLABO, ADRESSELABO, VILLE, NUMEROTEL,NB_CHERCHEUR,EMAIL,SITE_INTERNET) VALUES (3,'Labo 4','Adresse','Ville','0123456589',20,'labo4@email.com','www.labo4.fr');
DELETE FROM LABORATOIRE WHERE IDLABORATOIRE=3;

INSERT INTO PEA(ID_PEA,DATEPEA,MENTION,OBSERVATION)VALUES (4,TO_DATE('21112023','DDMMYYYY'),'Santé','Bon résultat');
DELETE FROM PEA WHERE ID_PEA=4;

INSERT INTO ANIMALERIE(ID_ANIMALERIE,GENRE_SOURIS,NB_SOURIS,ID_PEA,IDLABORATOIRE) VALUES (4,'Femelle',20,0,0);
DELETE  FROM ANIMALERIE WHERE ID_ANIMALERIE=4;

INSERT INTO CONTRATCHERCHEUR_INGE(IDCONTRAT,SECTEUR,TYPE_CONTRAT) VALUES (4,'Santé','CDI');
DELETE  FROM CONTRATCHERCHEUR_INGE WHERE IDCONTRAT=4;

INSERT INTO THESECHERCHEUR(IDTHESEC,DATE_DEBUT,DATE_FIN) VALUES (4,TO_DATE('01092023','DDMMYYYY'),TO_DATE('01092026','DDMMYYYY'));
DELETE  FROM THESECHERCHEUR WHERE IDTHESEC=4;

INSERT INTO UNIVERSITECHERCHEUR(IDUNIVERSITECHERCHEUR,ADRESSEUNIVERSITE,NB_HEURESC) VALUES (4,'Rue des Crayères, 51100 Reims',20);
DELETE  FROM UNIVERSITECHERCHEUR WHERE IDUNIVERSITECHERCHEUR=4;

INSERT INTO TACHE(ID_TACHE,NOM_TACHE) VALUES (6,'Tache test');
DELETE  FROM TACHE WHERE ID_TACHE=6;

INSERT INTO CHERCHEUR(IDCHERCHEUR, NOMCHERCHEUR, STATUTCHERCHEUR, PRENOMCHERCHEUR, AGECHERCHEUR,IDLABORATOIRE) VALUES (22,'SUpprimer','Non','Chercheur',30,0);
DELETE FROM CHERCHEUR WHERE IDCHERCHEUR=22;

INSERT INTO FOURNISSEUR(IDFOURNISSEUR,NOMFOURNISSEUR,ADRESSEFOURNISSEUR,TELFOURNISSEUR,EMAIL_FOURNISSEUR) VALUES (4,'Fournirien','1 rue de Reims','0322767589','fournirien@email.com');
DELETE FROM FOURNISSEUR WHERE IDFOURNISSEUR=4;

INSERT INTO CONSOMMABLES(IDCONSOMMABLE,CONTENANCE_TAILLE,NOMCONSOMMABLE,LOCALISATIONCONSOMMABLE) VALUES (10,'S','Lunettes','Placard B');
DELETE FROM CONSOMMABLES WHERE IDCONSOMMABLE=10;

INSERT INTO PRODUITSCHIMIQUES(IDPRODUITCHIMIQUE,NOMPRODUITCHIMIQUE,CONCENTRATIONPRODUITCHIMIQUE,CONTRES_INDICATIONS,TEMPERATURE_UTILISATION,LOCALISATIONPRODUITCHIMIQUE) VALUES(10,'Acide Sulfurique','37%','Ne pas inhaler','20 °C','Stockage A6');
DELETE FROM PRODUITCHIMIQUES WHERE IDPRODUITCHIMIQUE=10;

INSERT INTO MATERIEL_BIOLOGIE_MOLECULAIRE(ID_MAT_BIO,NOM_MAT_BIO,LOCALISATION_MAT_BIO) VALUES (10,'Lampe UV','Stockage MB6');
DELETE FROM MATERIEL_BIOLOGIE_MOLECULAIRE WHERE ID_MAT_BIO=10;

INSERT INTO CULTURECELLULAIRE(IDCULTURECELLULAIRE,NOMCULTURECELL,CONCENTRATIONCULTURECELLULAIRE,LOCALISATIONCULTURECELLULAIRE) VALUES (10,'Culture FQD','20%','Chambre Froide 2');
DELETE FROM CULTURECELLULAIRE WHERE IDCULTURECELLULAIRE=10;

INSERT INTO ENZYMES_RESTRICTION(ID_ENZYME_RESTRICTION,NUMERO_CONTAINER,NOM_ENZYME,CONCENTRATIONENZYME,TEMPERATURE_UTILISATION,NUMERO_BOITE) VALUES(10,1,'iUO','50%','20 °C',2);
DELETE FROM ENZYMES_RESTRICTION WHERE ID_ENZYME_RESTRICTION=10;

INSERT INTO EXPERIENCE(IDEXPERIENCE,BUT,DUREEPREPARATION,DUREEINCUBATION,RESULTAT) VALUES (10,'Créer organisme de synthèse','3 jours','1 mois','Echec');
DELETE FROM EXPERIENCE WHERE EXPERIENCE=10;

INSERT INTO PROJET(IDPROJET,SUJET,NB_PUBLICATIONS,DATEDEBUT,STATUT,IDEXPERIENCE) VALUES (10, 'Recherches sur le cancer des poumons', 4, TO_DATE('01022023','DDMMYYYY'),'En Cours',0);
DELETE FROM PROJET WHERE IDPROJET=10;

INSERT INTO EQUIPE(IDEQUIPE,IDPROJET,IDCHERCHEUR) VALUES (10,0,3);
DELETE FROM EQUIPE WHERE IDEQUIPE=10;

INSERT INTO ETRE_MEMBRE(IDCHERCHEUR,IDEQUIPE) VALUES (22,0);
DELETE FROM ETRE_MEMBRE WHERE IDCHERCHEUR=22 AND IDEQUIPE=0;

INSERT INTO EST_RESPONSABLE(IDCHERCHEUR,ID_TACHE) VALUES (22,3);
DELETE FROM EST_RESPONSABLE WHERE IDCHERCHEUR=22 AND IDTACHE=3;

INSERT INTO REUNION_LABORATOIRE(IDREUNION,DATEREUNION,HEUREREUNION,SALLEREUNION,IDLABORATOIRE) VALUES (22,TO_DATE('24112023','DDMMYYYY'),TO_DATE('4:00','HH:MI'),'Salle 8',0);
DELETE FROM REUNION_LABORATOIRE WHERE IDREUNION=22;

INSERT INTO PARTICIPER_REUNION(IDCHERCHEUR,IDREUNION) VALUES (22,3);
DELETE FROM PARTICIPER_REUNION WHERE IDCHERCHEUR=22 AND IDREUNION=3;

INSERT INTO PRODUIT(ID_PRODUIT,NB_RESTANT_PRODUIT,IDCHERCHEUR,IDLABORATOIRE,IDPRODUITCHIMIQUE) VALUES (22,20,2,0,0);
DELETE FROM PRODUIT WHERE IDPRODUIT=22;

INSERT INTO RESERVATION(ID_RESERVATION,DATE_RESERVATION,HEURE_RESERVATION,IDCHERCHEUR,IDLABORATOIRE) VALUES (22,TO_DATE('15112023','DDMMYYYY'),TO_DATE('4:00','HH:MI'),4,0);
DELETE FROM RESERVATION WHERE ID_RESERVATION=22;

INSERT INTO RESERVER_PRODUIT(ID_RESERVATION,ID_PRODUIT) VALUES (22,1);
DELETE FROM RESERVER_PRODUIT WHERE ID_RESERVATION=22 AND ID_PRODUIT=1;

INSERT INTO UTILISER(IDEXPERIENCE,ID_PRODUIT) VALUES (22,1);
DELETE FROM UTILISER WHERE IDEXPERIENCE=22 AND ID_PRODUIT=1;

INSERT INTO COMMANDE(IDCOMMANDE,DATECOMMANDE,DATELIVRAISON,IDLABORATOIRE,IDFOURNISSEUR,ID_PRODUIT) VALUES (22,TO_DATE('15112023','DDMMYYYY'),TO_DATE('20112023','DDMMYYYY'),0,0,0);
DELETE FROM COMMANDE WHERE IDCOMMANDE=22;

--Pour supprimer directement les tables--
DROP TABLE Est_responsable;
DROP TABLE Etre_membre;
DROP TABLE Utiliser;
DROP TABLE Participer_reunion;
DROP TABLE Reserver_produit;
DROP TABLE Commande;
DROP TABLE Reservation;
DROP TABLE Produit;
DROP TABLE Animalerie;
DROP TABLE Equipe;
DROP TABLE Chercheur;
DROP TABLE Tache;
DROP TABLE Enzymes_Restriction;
DROP TABLE reunion_laboratoire;
DROP TABLE PEA;
DROP TABLE Fournisseur;
DROP TABLE Materiel_biologie_moleculaire;
DROP TABLE Consommables;
DROP TABLE ProduitsChimiques;
DROP TABLE CultureCellulaire;
DROP TABLE Projet;
DROP TABLE Experience;
DROP TABLE ContratChercheur_Inge;
DROP TABLE theseChercheur;
DROP TABLE UniversiteChercheur;
DROP TABLE Laboratoire;